../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00dbac0
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00dbaf0
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00dbb08
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00dbc30
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00dbc68
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00dbcb8
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00dbe44
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00dbe94
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00dbebc
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00dc0bc
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00dc0e4
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00dc2c8
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00dc8d8
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00dc10c
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00dc15c
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00dc094
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00dc134
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00dc250
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00dc278
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00dc300
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00dc328
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00dc350
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00dcc54
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00dcc74
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00dce78
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00dcec8
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00e8220
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00e8240
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00ec790
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00ec934
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00ec934
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00ec934
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00ec934
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00edb14
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00ef898
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00efac0
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00efb50
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00efbc8
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00efd6c
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00efdac
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00f1b9c
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00f1b38
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00f1c30
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00f1ce0
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00f1e34
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00f1f7c
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00f2a70
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00f17d4
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00f21d0
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00f24ec
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00f27b4
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00f128c
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00f144c
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00f171c
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00f188c
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00f256c
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00f1984
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00f2230
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00f2308
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00f2664
../tools/mkscript/mkscript ../baserom.gba -s ../mksc.sym -d 0x00f2664